name = "GPDiffEq"
uuid = "4de859cf-bf9a-4c94-a796-5dda04c77145"
authors = ["Steffen Ridderbusch <steffen@robots.ox.ac.uk\n>"]
version = "0.1.0"

[deps]
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
